name: long_shadows_clock
description: Flutter Clock challenge taken by Ianko Leite.
version: 1.0.0

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_clock_helper:
    git:
      url: https://github.com/flutter/flutter_clock.git
      path: flutter_clock_helper
  intl: ^0.16.0

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: BungeeShade
      fonts: [asset: fonts/BungeeShade-Regular.ttf]
